version: "3.7"

services:
  my-backend:
    build: 
      context: ./class
      dockerfile: dockerfile
    volumes:
      - ./class/app:/my-backend/app
    ports:
      - 3000:3000
    env_file:
      - ./class/.env.docker

  my-mariadb:
    image: mariadb:latest
    environment:  # 올바른 키워드는 environment입니다.
      MARIADB_DATABASE: "onetomanydocker"
      MARIADB_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306



